#!/usr/bin/env node
/**
 * build.js — Generates data.js and prompts/by-app/, prompts/by-role/ README files
 * from YAML-frontmatter markdown files in prompts/_canonical/.
 *
 * Usage: node build.js
 *
 * Expected YAML frontmatter format in prompts/_canonical/*.md:
 *   ---
 *   title: Prompt Title
 *   app: outlook           # one of the supported app keys
 *   role: executive        # one of the supported role keys
 *   difficulty: beginner   # beginner / intermediate / advanced
 *   use_case: Short description of what this prompt does
 *   ---
 *   Prompt body text...
 */

const fs = require('fs');
const path = require('path');

// ─── Configuration ───────────────────────────────────────────────────

const CANONICAL_DIR = path.join(__dirname, 'prompts', '_canonical');
const BY_APP_DIR = path.join(__dirname, 'prompts', 'by-app');
const BY_ROLE_DIR = path.join(__dirname, 'prompts', 'by-role');
const DATA_JS_PATH = path.join(__dirname, 'data.js');

const APPS = {
  'outlook':          { display: 'Outlook',          color: '#3B82F6' },
  'excel':            { display: 'Excel',            color: '#10B981' },
  'teams':            { display: 'Microsoft Teams',  color: '#8B5CF6' },
  'word':             { display: 'Word',             color: '#2563EB' },
  'powerpoint':       { display: 'PowerPoint',       color: '#F59E0B' },
  'security-copilot': { display: 'Security Copilot', color: '#EF4444' },
  'cross-app':        { display: 'Cross-App',        color: '#06B6D4' },
};

const ROLES = {
  'executive':               { display: 'Executive' },
  'manager':                 { display: 'Manager' },
  'sales':                   { display: 'Sales' },
  'marketing':               { display: 'Marketing' },
  'operations':              { display: 'Operations' },
  'finance-hr':              { display: 'Finance & HR' },
  'legal-compliance':        { display: 'Legal & Compliance' },
  'security':                { display: 'Security' },
  'assistant':               { display: 'Assistant' },
  'research-dev':            { display: 'Research & Dev' },
  'consulting':              { display: 'Consulting' },
  'project-leadership':      { display: 'Project Leadership' },
  'customer-success':        { display: 'Customer Success' },
  'commercial-ops':          { display: 'Commercial Ops' },
  'supply-chain':            { display: 'Supply Chain' },
  'engineering-construction': { display: 'Engineering & Construction' },
  'admin':                   { display: 'Admin' },
  'general':                 { display: 'General' },
};

const APP_KEYS = Object.keys(APPS);
const ROLE_KEYS = Object.keys(ROLES);

const HEADER_MD     = '<!-- Auto-generated by build.js — do not edit manually -->\n<!-- Run: node build.js -->\n';
const HEADER_JS     = '// Auto-generated by build.js — do not edit manually\n// Run: node build.js\n';

// ─── Helpers ─────────────────────────────────────────────────────────

/**
 * Parse YAML frontmatter from markdown content using a simple regex.
 * Returns { frontmatter: { key: value, ... }, body: string }.
 */
function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!match) {
    return { frontmatter: {}, body: content };
  }

  const yamlBlock = match[1];
  const body = content.slice(match[0].length);
  const frontmatter = {};

  for (const line of yamlBlock.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const kvMatch = trimmed.match(/^([a-zA-Z_][a-zA-Z0-9_-]*)\s*:\s*(.*)$/);
    if (kvMatch) {
      let value = kvMatch[2].trim();
      // Strip surrounding quotes
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      frontmatter[kvMatch[1]] = value;
    }
  }

  return { frontmatter, body: body.trim() };
}

/**
 * Split prompt body into context and prompt sections.
 * Expected format:
 *   ## Context
 *   <context text>
 *
 *   ## Prompt
 *   ```
 *   <prompt text>
 *   ```
 */
function parseContextAndPrompt(body) {
  // Try to match ## Context ... ## Prompt pattern
  const match = body.match(/##\s*Context\s*\n([\s\S]*?)\n##\s*Prompt\s*\n```?\s*\n?([\s\S]*?)\s*```?\s*$/);
  if (match) {
    return { context: match[1].trim(), prompt: match[2].trim() };
  }

  // Fallback: if no ## Context/## Prompt structure, treat entire body as prompt
  return { context: '', prompt: body };
}

function slugFromFilename(filename) {
  return path.basename(filename, '.md');
}

/**
 * Normalize a title for deduplication grouping.
 * Removes articles, lowercases, strips punctuation, and slugifies.
 * Examples:
 *   "The Thread Dissection Surgeon" → "thread-dissection-surgeon"
 *   "Thread Dissection Surgeon"     → "thread-dissection-surgeon"
 */
function normalizeTitleForGrouping(title) {
  if (!title) return '';
  return title
    .toLowerCase()
    .replace(/\b(the|a|an)\b\s*/gi, '')  // Remove leading articles
    .replace(/[^\w\s-]/g, '')              // Remove punctuation
    .replace(/\s+/g, '-')                  // Replace spaces with hyphens
    .replace(/-+/g, '-')                   // Collapse multiple hyphens
    .replace(/^-|-$/g, '');                // Trim leading/trailing hyphens
}

/**
 * Group prompts by normalized title and mark primary variant.
 * Primary = variant with longest prompt content.
 * Returns { promptsData, duplicateGroups } where duplicateGroups maps groupId → [slugs].
 */
function deduplicatePrompts(rawPrompts) {
  // Build groups by normalized title
  const groups = {};
  for (const p of rawPrompts) {
    const groupId = normalizeTitleForGrouping(p.title);
    if (!groupId) continue;
    if (!groups[groupId]) groups[groupId] = [];
    groups[groupId].push(p);
  }

  // Find primary variant for each group (longest prompt content)
  const primaryMap = {};
  const duplicateGroups = {};

  for (const [groupId, variants] of Object.entries(groups)) {
    // Sort by prompt length descending
    variants.sort((a, b) => (b.prompt || '').length - (a.prompt || '').length);
    const primarySlug = variants[0].slug;
    primaryMap[groupId] = primarySlug;

    // Track groups with multiple variants
    if (variants.length > 1) {
      duplicateGroups[groupId] = variants.map(v => v.slug);
    }
  }

  return { primaryMap, duplicateGroups, groupCount: Object.keys(groups).length };
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function safeDisplay(key, map) {
  return (map[key] && map[key].display) ? map[key].display : key;
}

// ─── Main ────────────────────────────────────────────────────────────

function main() {
  // 1. Read all .md files from _canonical/
  if (!fs.existsSync(CANONICAL_DIR)) {
    console.warn('[WARN] prompts/_canonical/ does not exist yet.');
    console.warn('[WARN] Creating output directories with empty/placeholder files.\n');
    ensureDir(BY_APP_DIR);
    ensureDir(BY_ROLE_DIR);
    writeDataJs([], {});
    writeEmptyAppLanding();
    writeEmptyRoleLanding();
    console.log('\nDone — no prompts found. Add .md files to prompts/_canonical/ and re-run.');
    return;
  }

  const files = fs.readdirSync(CANONICAL_DIR).filter(f => f.endsWith('.md'));

  if (files.length === 0) {
    console.warn('[WARN] No .md files found in prompts/_canonical/.');
    ensureDir(BY_APP_DIR);
    ensureDir(BY_ROLE_DIR);
    writeDataJs([], {});
    writeEmptyAppLanding();
    writeEmptyRoleLanding();
    console.log('\nDone — no prompts found. Add .md files to prompts/_canonical/ and re-run.');
    return;
  }

  const rawPrompts = [];

  for (const file of files) {
    const filePath = path.join(CANONICAL_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const { frontmatter, body } = parseFrontmatter(content);
    const slug = slugFromFilename(file);
    const { context, prompt } = parseContextAndPrompt(body);

    const promptObj = {
      slug,
      ...frontmatter,
      context,
      prompt,
    };
    rawPrompts.push(promptObj);
  }

  // Validate apps and roles against supported lists
  for (const p of rawPrompts) {
    if (p.app && !APPS[p.app]) {
      console.warn(`  [WARN] Unknown app "${p.app}" in ${p.slug}.md. Using as-is.`);
    }
    if (p.role && !ROLES[p.role]) {
      console.warn(`  [WARN] Unknown role "${p.role}" in ${p.slug}.md. Using as-is.`);
    }
  }

  // Deduplicate: group by normalized title, mark primary variant
  const { primaryMap, duplicateGroups } = deduplicatePrompts(rawPrompts);
  const uniqueCount = Object.keys(primaryMap).length;
  const dupCount = Object.keys(duplicateGroups).length;
  if (dupCount > 0) {
    console.log(`  Deduplication: ${dupCount} groups with duplicates (${rawPrompts.length} total → ${uniqueCount} unique)`);
    for (const [groupId, slugs] of Object.entries(duplicateGroups)) {
      console.log(`    "${groupId}": ${slugs.join(', ')}`);
    }
  }

  // 2. Build GROUPS_META (group → category → { count, color })
  //    Groups = apps, categories = roles
  const groupsMeta = {};

  for (const p of rawPrompts) {
    const appKey = p.app && APPS[p.app] ? p.app : 'cross-app';
    const roleKey = p.role && ROLES[p.role] ? p.role : 'general';
    const appDisplay = APPS[appKey].display;
    const roleDisplay = ROLES[roleKey].display;
    const color = APPS[appKey].color;

    if (!groupsMeta[appDisplay]) {
      groupsMeta[appDisplay] = {};
    }
    if (!groupsMeta[appDisplay][roleDisplay]) {
      groupsMeta[appDisplay][roleDisplay] = { count: 0, color };
    }
    groupsMeta[appDisplay][roleDisplay].count++;
  }

  // 3. Build PROMPTS_DATA for the web UI (backward-compatible with index.html)
  const promptsData = rawPrompts.map(p => {
    const appKey = p.app && APPS[p.app] ? p.app : 'cross-app';
    const roleKey = p.role && ROLES[p.role] ? p.role : 'general';
    const appMeta = APPS[appKey];
    const roleMeta = ROLES[roleKey];
    const groupId = normalizeTitleForGrouping(p.title);
    const isPrimary = primaryMap[groupId] === p.slug;
    const variantCount = duplicateGroups[groupId] ? duplicateGroups[groupId].length : 1;

    return {
      id: p.slug,
      title: p.title || '',
      useCase: p.use_case || p.useCase || '',
      context: p.context || '',
      prompt: p.prompt || '',
      group: appMeta.display,
      category: roleMeta.display,
      color: appMeta.color,
      personas: [roleMeta.display],
      tags: [appMeta.display, roleMeta.display].filter(Boolean),
      subcategory: p.difficulty || '',
      // Raw frontmatter fields included for downstream use
      slug: p.slug,
      app: appKey,
      role: roleKey,
      difficulty: p.difficulty || '',
      use_case: p.use_case || '',
      // Deduplication fields
      groupId,
      isPrimary,
      variantCount,
      variantSlugs: duplicateGroups[groupId] || [p.slug],
    };
  });

  // 4. Group by app and role for README generation
  const byApp = {};
  const byRole = {};

  for (const p of rawPrompts) {
    const appKey = p.app && APPS[p.app] ? p.app : 'cross-app';
    const roleKey = p.role && ROLES[p.role] ? p.role : 'general';

    if (!byApp[appKey]) byApp[appKey] = [];
    byApp[appKey].push({ ...p, _appKey: appKey, _roleKey: roleKey });

    if (!byRole[roleKey]) byRole[roleKey] = [];
    byRole[roleKey].push({ ...p, _appKey: appKey, _roleKey: roleKey });
  }

  // 5. Write data.js
  writeDataJs(promptsData, groupsMeta);

  // 6. Write by-app/ READMEs
  writeAppLanding(byApp);
  for (const appKey of APP_KEYS) {
    if (byApp[appKey]) {
      writeAppReadme(appKey, byApp[appKey]);
    }
  }

  // 7. Write by-role/ READMEs
  writeRoleLanding(byRole);
  for (const roleKey of ROLE_KEYS) {
    if (byRole[roleKey]) {
      writeRoleReadme(roleKey, byRole[roleKey]);
    }
  }

  // Summary
  const total = promptsData.length;
  const appsUsed = Object.keys(byApp).length;
  const rolesUsed = Object.keys(byRole).length;
  console.log(`\nDone: ${total} prompts (${uniqueCount} unique) across ${appsUsed} apps and ${rolesUsed} roles.`);
}

// ─── data.js generation ──────────────────────────────────────────────

function writeDataJs(promptsData, groupsMeta) {
  // Compute APPS_META and ROLES_META from promptsData
  const appsMeta = {};
  const rolesMeta = {};

  for (const key of APP_KEYS) {
    appsMeta[key] = { display: APPS[key].display, count: 0, color: APPS[key].color };
  }
  for (const key of ROLE_KEYS) {
    rolesMeta[key] = { display: ROLES[key].display, count: 0 };
  }

  for (const p of promptsData) {
    const appKey = p.app && APPS[p.app] ? p.app : 'cross-app';
    const roleKey = p.role && ROLES[p.role] ? p.role : 'general';
    if (appsMeta[appKey]) appsMeta[appKey].count++;
    if (rolesMeta[roleKey]) rolesMeta[roleKey].count++;
  }

  const output = `${HEADER_JS}const PROMPTS_DATA = ${JSON.stringify(promptsData, null, 2)};\n\nconst GROUPS_META = ${JSON.stringify(groupsMeta, null, 2)};\n\nconst APPS_META = ${JSON.stringify(appsMeta, null, 2)};\n\nconst ROLES_META = ${JSON.stringify(rolesMeta, null, 2)};\n`;
  fs.writeFileSync(DATA_JS_PATH, output, 'utf-8');
  console.log(`  Written → data.js (${promptsData.length} prompts)`);
}

// ─── App landing page ────────────────────────────────────────────────

function writeEmptyAppLanding() {
  ensureDir(BY_APP_DIR);
  const lines = [
    HEADER_MD,
    '# Prompts by App',
    '',
    'Browse prompts organized by Microsoft 365 application.',
    '',
    '| App | Prompts |',
    '| --- | ------- |',
  ];
  for (const key of APP_KEYS) {
    lines.push(`| ${APPS[key].display} | 0 |`);
  }
  lines.push('');
  fs.writeFileSync(path.join(BY_APP_DIR, 'README.md'), lines.join('\n'), 'utf-8');
  console.log('  Written → prompts/by-app/README.md (empty)');
}

function writeAppLanding(byApp) {
  ensureDir(BY_APP_DIR);
  const lines = [
    HEADER_MD,
    '# Prompts by App',
    '',
    'Browse prompts organized by Microsoft 365 application.',
    '',
    '| App | Prompts |',
    '| --- | ------- |',
  ];
  for (const key of APP_KEYS) {
    const prompts = byApp[key] || [];
    const count = prompts.length;
    const display = APPS[key].display;
    const link = count > 0 ? `[${display}](${key}/README.md)` : display;
    lines.push(`| ${link} | ${count} |`);
  }
  lines.push('');
  const content = lines.join('\n');
  fs.writeFileSync(path.join(BY_APP_DIR, 'README.md'), content, 'utf-8');
  console.log('  Written → prompts/by-app/README.md');
}

function writeAppReadme(appKey, appPrompts) {
  const appDir = path.join(BY_APP_DIR, appKey);
  ensureDir(appDir);
  const appMeta = APPS[appKey];
  const sorted = [...appPrompts].sort((a, b) => (a.title || '').localeCompare(b.title || ''));

  const lines = [
    HEADER_MD,
    `# ${appMeta.display} — Prompts`,
    '',
    `Prompt collection for **${appMeta.display}**.`,
    '',
    '| Title | Use Case | Roles | Difficulty |',
    '| ----- | -------- | ----- | ---------- |',
  ];

  for (const p of sorted) {
    const title = p.title || 'Untitled';
    const slug = p.slug || '';
    const link = `[${title}](../../_canonical/${slug}.md)`;
    const useCase = p.use_case || p.useCase || '';
    const roleDisplay = safeDisplay(p._roleKey || p.role, ROLES);
    const difficulty = p.difficulty || '';
    lines.push(`| ${link} | ${useCase} | ${roleDisplay} | ${difficulty} |`);
  }

  lines.push('');
  fs.writeFileSync(path.join(appDir, 'README.md'), lines.join('\n'), 'utf-8');
  console.log(`  Written → prompts/by-app/${appKey}/README.md`);
}

// ─── Role landing page ───────────────────────────────────────────────

function writeEmptyRoleLanding() {
  ensureDir(BY_ROLE_DIR);
  const lines = [
    HEADER_MD,
    '# Prompts by Role',
    '',
    'Browse prompts organized by professional role.',
    '',
    '| Role | Prompts |',
    '| ---- | ------- |',
  ];
  for (const key of ROLE_KEYS) {
    lines.push(`| ${ROLES[key].display} | 0 |`);
  }
  lines.push('');
  fs.writeFileSync(path.join(BY_ROLE_DIR, 'README.md'), lines.join('\n'), 'utf-8');
  console.log('  Written → prompts/by-role/README.md (empty)');
}

function writeRoleLanding(byRole) {
  ensureDir(BY_ROLE_DIR);
  const lines = [
    HEADER_MD,
    '# Prompts by Role',
    '',
    'Browse prompts organized by professional role.',
    '',
    '| Role | Prompts |',
    '| ---- | ------- |',
  ];
  for (const key of ROLE_KEYS) {
    const prompts = byRole[key] || [];
    const count = prompts.length;
    const display = ROLES[key].display;
    const link = count > 0 ? `[${display}](${key}/README.md)` : display;
    lines.push(`| ${link} | ${count} |`);
  }
  lines.push('');
  const content = lines.join('\n');
  fs.writeFileSync(path.join(BY_ROLE_DIR, 'README.md'), content, 'utf-8');
  console.log('  Written → prompts/by-role/README.md');
}

function writeRoleReadme(roleKey, rolePrompts) {
  const roleDir = path.join(BY_ROLE_DIR, roleKey);
  ensureDir(roleDir);
  const roleMeta = ROLES[roleKey];
  const sorted = [...rolePrompts].sort((a, b) => (a.title || '').localeCompare(b.title || ''));

  const lines = [
    HEADER_MD,
    `# ${roleMeta.display} — Prompts`,
    '',
    `Prompt collection for **${roleMeta.display}**.`,
    '',
    '| Title | App | Use Case | Difficulty |',
    '| ----- | --- | -------- | ---------- |',
  ];

  for (const p of sorted) {
    const title = p.title || 'Untitled';
    const slug = p.slug || '';
    const link = `[${title}](../../_canonical/${slug}.md)`;
    const appDisplay = safeDisplay(p._appKey || p.app, APPS);
    const useCase = p.use_case || p.useCase || '';
    const difficulty = p.difficulty || '';
    lines.push(`| ${link} | ${appDisplay} | ${useCase} | ${difficulty} |`);
  }

  lines.push('');
  fs.writeFileSync(path.join(roleDir, 'README.md'), lines.join('\n'), 'utf-8');
  console.log(`  Written → prompts/by-role/${roleKey}/README.md`);
}

// ─── Execute ─────────────────────────────────────────────────────────

main();
